### ISSUE TITLE
Client sends to wrong address on server restart

### ISSUE THREAD

**Issue by flub** [n0-computer/iroh#3602]
When a client and server are connected using a direct address the client has the server's address stored in the "best address".  If you now restart the server and ask the client to create a new connection to the re-started server, which is using the same EndpointId but a different IP bind address, the connection is very slow.

The issue is that the "best address" is still known and is considered valid for 6.5s.  So even if the new connect call is given the new correct IP address of the server, it will keep sending to the previously chosen "best addr" until the 6.5s time out.  Only then will it fall back to the relay and manage to re-establish a connection.

**Comment by Arqu** [comment]
Related https://github.com/n0-computer/iroh/issues/3504

**Comment by matheus23** [comment]
Should we perhaps clear the best address once the last connection to another endpoint closes?
If that's too much, perhaps we could designate a special QUIC close code to mean "endpoint is shutting down" and interpret only that in a way that makes us reset the best address?

Is this fixed by multipath? IIUC, in the multipath world we still want to track the recently validated paths, right? And we'd use that info to dial *only* the direct addr if that's the recently last validated path we had. So I think we need to consider fixing this with multipath, too.

**Comment by flub** [comment]
It is not fixed per se on multipath.

- We should definitely drop the selected address when the last connection closes.
- Otherwise I think I'd like to get an event from Quinn when the PTO fires: this is when a packet should have been ACKed, but hasn't been yet.  QUIC then re-sends the packet but we need to do something smarter at this point:
  - perhaps send the tial-loss probes on all paths
  - start discovery again
  - try new paths, which internally still arrive from "add_node_addr", that is either from the addr passed to connect calls or discovery.

And yeah, we need to work this out on the feat-multipath branch.

**Comment by matheus23** [comment]
Closed by #3650 

It doesn't implement the PTO event stuff that @flub described above, but it doesn't exhibit the issue in the title anymore.

Also, I think that although there's no PTO events, when there's still a connection to the peer, the `selected_path` should get an event when the path closes, and that should be informed by PTO on the quinn side. So indirectly, these events might already be picked up?

Anyhow - closing this.
